[package]
name = "urcu-bp-sys"
license = "GPL-3.0-or-later"
version = "0.1.0"
edition = "2021"

[package.metadata.pkg-config]
liburcu-bp = "0.11"

[dependencies]
urcu-sys = { path = "../urcu-sys" }

[build-dependencies]
bindgen = "0.69"
metadeps = "1"