stages:
  - tool
  - build
  - check

#############
# tool jobs #
#############

image:rust:
  stage: tool
  image:
    name: quay.io/podman/stable:latest
    docker:
      user: podman
  script:
    - ./.gitlab/build-image.sh rust

image:urcu-shared:
  needs: [image:rust]
  stage: tool
  image:
    name: quay.io/podman/stable:latest
    docker:
      user: podman
  script:
    - ./.gitlab/build-image.sh urcu-shared

image:urcu-static:
  needs: [image:rust]
  stage: tool
  image:
    name: quay.io/podman/stable:latest
    docker:
      user: podman
  script:
    - ./.gitlab/build-image.sh urcu-static

##############
# build jobs #
##############

build:urcu-static:
  needs: [image:urcu-static]
  stage: build
  image: ${CI_REGISTRY_IMAGE}/urcu-static:0.1.0-${CI_COMMIT_SHORT_SHA}
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - time cargo build --release --examples --tests --features static
  artifacts:
    paths:
      - target/

build:urcu-shared:
  needs: [image:urcu-shared]
  stage: build
  image: ${CI_REGISTRY_IMAGE}/urcu-shared:0.1.0-${CI_COMMIT_SHORT_SHA}
  script:
    - time cargo build --release --examples --tests
  artifacts:
    paths:
      - target/

##############
# check jobs #
##############

test:urcu-static:
  needs: [build:urcu-static]
  stage: check
  image: ${CI_REGISTRY_IMAGE}/urcu-static:0.1.0-${CI_COMMIT_SHORT_SHA}
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - time cargo nextest run --release --profile=ci --features static
  artifacts:
    paths:
      - target/nextest/ci/junit.xml
    reports:
      junit: target/nextest/ci/junit.xml

test:urcu-shared:
  needs: [build:urcu-shared]
  stage: check
  image: ${CI_REGISTRY_IMAGE}/urcu-shared:0.1.0-${CI_COMMIT_SHORT_SHA}
  script:
    - time cargo nextest run --release --profile=ci
  artifacts:
    paths:
      - target/nextest/ci/junit.xml
    reports:
      junit: target/nextest/ci/junit.xml
