[workspace]
resolver = "2"
members = [
    "urcu-bp-sys",
    "urcu-common-sys",
    "urcu-cds-sys",
    "urcu-mb-sys",
    "urcu-memb-sys",
    "urcu-qsbr-sys",
    "urcu-src",
    "urcu-sys",
    "urcu",
]

[profile.release]
opt-level = 2
lto = true
