[package]
name = "urcu-sys"
license = "GPL-3.0-or-later"
version = "0.1.0"
edition = "2021"

[package.metadata.pkg-config]
liburcu = "0.11"

[build-dependencies]
bindgen = { version = "0.69", features = ["experimental"] }
cc = "1"
metadeps = "1"